### ISSUE TITLE
Wrong usernsme

### ISSUE THREAD

**Issue by ashjk6** [Hazza3100/TikTok-report-bot#10]
[ ? ] Threads > 10
[ ? ] Use proxies (y/n) > y
[ x ] Username Invalid
sh: title: inaccessible or not found
sh: Success:: inaccessible or not found
sh: Errors:: inaccessible or not found
sh: title: inaccessible or not found
sh: Success:: inaccessible or not found
sh: Errors:: inaccessible or not found
[ x ] Error
[ x ] Error
[ x ] Error
[ x ] Error
sh: title: inaccessible or not found
sh: Success:: inaccessible or not found
sh: Errors:: inaccessible or not found                     [ x ] Error
[ x ] Error
[ x ] Error
[ x ] Error
[ x ] Error
[ x ] Error                                                ~/TikTok-report-bot $
Using termux

**Comment by Hazza3100** [comment]
Hi this source is outdated.
