### ISSUE TITLE
Bot is patched

### ISSUE THREAD

**Issue by VSCODE-0000** [Hazza3100/TikTok-report-bot#7]
Bot is patched. I get an error.

`[ ? ] Threads > 1
[ ? ] Use proxies (y/n) > y
[ x ] Error`

**Comment by Hazza3100** [comment]
> Bot is patched. I get an error.
> 
> `[ ? ] Threads > 1 [ ? ] Use proxies (y/n) > y [ x ] Error`

Looks like scrape error, this project is no longer maintained.
